JeCenterWeb/Models/NotificationType.cs
using System.ComponentModel.DataAnnotations;

namespace JeCenterWeb.Models
{
    public class NotificationType : MasterModel
    {

        [Key]
        public int NotificationTypeId { get; set; }

        [Required]
        public string Type { get; set; }
    }
}

JeCenterWeb/Models/ViewModel/NotificationViewModel.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace JeCenterWeb.Models.ViewModel
{
    public class NotificationViewModel
    {
        public int NotificationId { get; set; }

        [Display(Name = " نوع الاشعار ")]
       
        public int NotificationTypeId { get; set; }

        public int GroupId { get; set; }

        [Display(Name = " العنوان ")]
        [Required]
        public string NotiTitel { get; set; }


        [Display(Name = " الاشعار ")]
        [Required]
        public string NotificationNote { get; set; }

        
    }
}

JeCenterWeb/Models/ViewModel/ReadedNotificationViewModel.cs
namespace JeCenterWeb.Models.ViewModel
{
    public class ReadedNotificationViewModel
    {
        public CNotifications? cNotifications {  get; set; } 
        public IEnumerable<NotificationUserSeen>? NotificationUserSeen { get; set; }

    }
}

JeCenterWeb/Areas/learning/Controllers/NotificationsController.cs
using JeCenterWeb.Data;
using JeCenterWeb.Migrations;
using JeCenterWeb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace JeCenterWeb.Areas.learning.Controllers
{
    [Area("learning")]
    [Authorize(Roles = "Student")]
    public class NotificationsController : Controller
    {
        string ControllerName = "الاشعارات ";
        string AppName = "السنتر";
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        public NotificationsController(ApplicationDbContext context,
          UserManager<ApplicationUser> userManager,
          SignInManager<ApplicationUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public async Task<IActionResult> Index()
        {
            ViewData["AppName"] = AppName;
            ViewData["ControllerName"] = ControllerName;
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ApplicationUser student = await _userManager.FindByIdAsync(userId);
            ViewData["UserName"] = student.FristName;
            var userbalance = await _context.UsersBalance.FindAsync(student.AccountID);
            ViewData["balance"] = userbalance.Balance * -1;

            var modellist = await _context.StudentNotifications
              .Where(t => t.StudentId == student.Id)
              .Include(t => t.GNotifications)
              .ToListAsync();
            return View(modellist);
        }

        public async Task<IActionResult> ReadNotification(int id)
        {
            ViewData["AppName"] = AppName;
            ViewData["ControllerName"] = ControllerName;

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            int uid = Convert.ToInt32(userId);

            var model = await _context.StudentNotifications
                .Where(t => t.StudentNotificationId == id)
                .Include(t => t.GNotifications)
                .FirstOrDefaultAsync();
            model.Seen = true;
            model.UpdateId = uid;
            model.UpdatedDate = DateTime.Now;

            _context.Update(model);
            await _context.SaveChangesAsync();


            return View(model);
        }
    }
}

JeCenterWeb/Areas/scp/Controllers/DiscussController.cs
using JeCenterWeb.Data;
using JeCenterWeb.Models;
using JeCenterWeb.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace JeCenterWeb.Areas.scp.Controllers
{
    [Area("scp")]
    [Authorize(Roles = "AdminSettings,PowerUser,SuperUser,User")]
    public class DiscussController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger<TeachersController> _logger;
        //  private readonly FinancialDocumentEntryRepository _repository;
        string ControllerName = "الإشعارات";
        string AppName = "الأدمن";
        public DiscussController(ApplicationDbContext context,
             UserManager<ApplicationUser> userManager,
             SignInManager<ApplicationUser> signInManager,
             ILogger<TeachersController> logger,
             IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _webHostEnvironment = webHostEnvironment;
            // _repository = repository;
            // FinancialDocumentEntryRepository repository

        }
        [Authorize(Roles = "AdminSettings,PowerUser")]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "AdminSettings,PowerUser,SuperUser,User")]
        public async Task<IActionResult> Notifications()
        {
            ViewData["AppName"] = AppName;
            ViewData["ControllerName"] = ControllerName;

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            int uid = Convert.ToInt32(userId);
            var modellist = await _context.UsersNotifications
                .Where(t => t.UserId == uid)
                .OrderByDescending(t => t.NotificationId)
                .Include(t => t.CNotifications)
                .ToListAsync();
            return View(modellist);
        }

        [Authorize(Roles = "AdminSettings,PowerUser,SuperUser,User")]
        public async Task<IActionResult> ReadNotification(int id)
        {
            ViewData["AppName"] = AppName;
            ViewData["ControllerName"] = ControllerName;

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            int uid = Convert.ToInt32(userId);

            var model = await _context.UsersNotifications
                .Where(t => t.UsersNotificationId == id)
                .Include(t => t.CNotifications)
                .FirstOrDefaultAsync();
            model.Seen = true;
            model.UpdateId = uid;
            model.UpdatedDate = DateTime.Now;

            _context.Update(model);
            await _context.SaveChangesAsync();


            return View(model);
        }

        [Authorize(Roles = "AdminSettings")]
        public async Task<IActionResult> ReadedNotification(int id)
        {
            ViewData["AppName"] = AppName;
            ViewData["ControllerName"] = ControllerName;

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            int uid = Convert.ToInt32(userId);
            ReadedNotificationViewModel notificationViewModel = new ReadedNotificationViewModel();


            notificationViewModel.cNotifications = await _context.CNotifications
                .Where(t => t.NotificationId == id)
                .FirstOrDefaultAsync();

            if(notificationViewModel.cNotifications == null)
            {
                return RedirectToAction(nameof(NotiEmp));
            }

            var usersnoti = await _context.UsersNotifications.Where(u => u.NotificationId == id).ToListAsync();

            List<NotificationUserSeen> seen = new List<NotificationUserSeen>();

            foreach (var item in usersnoti)
            {
                var usermodel = await _context.Users.Where(u => u.Id == item.UserId).FirstOrDefaultAsync();
                NotificationUserSeen userSeen = new NotificationUserSeen()
                {
                    UserId = item.UserId,
                    Seen = item.Seen,
                    SeenDate = item.UpdatedDate,
                    UserName = usermodel.FullName,
                };
                seen.Add(userSeen);
            }

            notificationViewModel.NotificationUserSeen = seen;

            return View(notificationViewModel);
        }
        

        // DeleteNotification
        [Authorize(Roles = "AdminSettings,PowerUser")]
        public async Task<IActionResult> DeleteNotification(int id)
        {
            ViewData["AppName"] = AppName;
            ViewData["ControllerName"] = ControllerName;

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            int uid = Convert.ToInt32(userId);
            

            var cNotifications = await _context.CNotifications
                .Where(t => t.NotificationId == id)
                .FirstOrDefaultAsync();

            if (cNotifications == null)
            {
                return RedirectToAction(nameof(NotiEmp));
            }
             

            return View(cNotifications);
        }


        // DeleteNotiEmp
        [Authorize(Roles = "AdminSettings,PowerUser")]
        [HttpPost]
        public async Task<IActionResult> DeleteNotiEmp(int id)
        {
            ViewData["AppName"] = AppName;
            ViewData["ControllerName"] = ControllerName;
 

            var cNotifications = await _context.CNotifications
                .Where(t => t.NotificationId == id)
                .FirstOrDefaultAsync();

            if (cNotifications == null)
            {
                return RedirectToAction(nameof(NotiEmp));
            }
            _context.Remove(cNotifications);
            await _context.SaveChangesAsync();


            return RedirectToAction(nameof(NotiEmp));
        }
        
        // NotiEmp
        [Authorize(Roles = "AdminSettings,PowerUser")]
        public async Task<IActionResult> NotiEmp()
        {
            ViewData["AppName"] = AppName;
            ViewData["ControllerName"] = ControllerName;
            var notiemp = await _context.CNotifications
                .OrderByDescending(n => n.NotificationId).ToListAsync();
            return View(notiemp);

        }

        // GET: scp/AddNotiGroup/Create
        [Authorize(Roles = "AdminSettings,PowerUser")]
        public async Task<IActionResult> AddNotiEmp()
        {
            return View();
        }

        // POST: scp/Departments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "AdminSettings,PowerUser")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddNotiEmp([Bind("NotificationId,NotiTitel,NotificationNote,Writed,Deleted,Active,CreateId,CreatedDate,UpdateId,UpdatedDate,DeleteId,DeletedDate")] CNotifications Notifications)
        {
            ViewData["AppName"] = AppName;
            ViewData["ControllerName"] = ControllerName;
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            int uid = Convert.ToInt32(userId);
            if (ModelState.IsValid)
            {
                Notifications.CreateId = Convert.ToInt32(userId);
                Notifications.UpdateId = Convert.ToInt32(userId);
                Notifications.DeleteId = Convert.ToInt32(userId);
                Notifications.UpdatedDate = DateTime.Now;
                Notifications.CreatedDate = DateTime.Now;
                Notifications.DeletedDate = DateTime.Now;
                Notifications.Active = true;
                _context.Add(Notifications);
                await _context.SaveChangesAsync();

                var emps = await _context.Users.Where(e => e.UserTypeId < 5 && e.Active == true).ToListAsync();

                foreach (var item in emps)
                {
                    UsersNotifications usersNotifications = new UsersNotifications()
                    {
                        UserId = item.Id,
                        NotificationId = Notifications.NotificationId,
                        Active = true,
                        CreateId = uid,
                        CreatedDate = DateTime.Now,
                        Seen = false,
                    };

                    _context.Add(usersNotifications);
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction(nameof(NotiEmp));
            }
            return View(Notifications);
        }

        // NotiGroup
        [Authorize(Roles = "AdminSettings,PowerUser")]
        public async Task<IActionResult> NotiGroup()
        {
            ViewData["AppName"] = AppName;
            ViewData["ControllerName"] = ControllerName;
            var notiemp = await _context.GNotifications
                .OrderByDescending(n => n.NotificationId).ToListAsync();
            return View(notiemp);
        }

        // GET: scp/AddNotiGroup/Create
        [Authorize(Roles = "AdminSettings,PowerUser")]
        public IActionResult AddNotiGroup()
        {
            ViewData["AppName"] = AppName;
            ViewData["ControllerName"] = ControllerName;
            ViewData["Id"] = new SelectList(_userManager.Users.Where(f => f.UserTypeId == 5), "Id", "FullName");

            return View();
        }

        // POST: scp/Departments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.

JeCenterWeb/Areas/scp/Views/Discuss/AddNotiEmp.cshtml
 @model JeCenterWeb.Models.CNotifications

@{
    ViewData["Title"] = "Notifications";
}


<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <partial name="_NotiMenu" />
            </div>
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">  إشعار جديد للموظفين </h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <form asp-action="AddNotiEmp">
                            
                            <div class="form-group">
                                <label asp-for="NotiTitel" class="control-label"></label>
                                <input asp-for="NotiTitel" class="form-control" />
                                <span asp-validation-for="NotiTitel" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="NotificationNote" class="control-label"></label>
                                <textarea id="textarea" asp-for="NotificationNote" placeholder="Blog Content" style="direction:rtl !important;"></textarea>
                                <script src="~/lib/tinymce/tinymce.min.js"></script>
                                <script>
                                    tinymce.init({
                                        selector: '#textarea', plugins: "tooltip print preview fullpage paste searchreplace autolink directionality visualblocks visualchars fullscreen image link media template codesample code table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists textcolor wordcount imagetools contextmenu colorpicker textpattern", toolbar1: 'formatselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat', height: "200", paste_data_images: true
                                    });

                                </script>

                                <span asp-validation-for="NotificationNote" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="إرسال" class="btn btn-primary" /> |
                                <a class="btn btn-dark" asp-action="Index"> رجوع </a>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>

JeCenterWeb/Areas/scp/Views/Discuss/DeleteNotification.cshtml
@model JeCenterWeb.Models.CNotifications


@{
    ViewData["Title"] = "Notifications";
}




<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <partial name="_NotiMenu" />
            </div>
            <div class="col-md-9">
                <div class="card card-primary card-outline">

                    <div class="card-header">
                        <h3 class="card-title"> الطلبة </h3>
                        <div class="card-tools">
                            <form asp-action="DeleteNotiEmp" asp-route-id="@Model.NotificationId" method="post">
                                <input type="hidden" name="@Model.NotificationId" />
                                <input type="submit" value="حذف" class="btn btn-danger" />
                            </form>
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <div class="mailbox-read-info">
                            <h5> @Model.NotiTitel</h5>
                            <h6>
                                <span class="mailbox-read-time float-right"> @Model.CreatedDate  </span>
                            </h6>
                        </div>
                        <div class="mailbox-read-message">
                            @Html.Raw(Model.NotificationNote)
                        </div>
                    </div>
                   
                </div>
            </div>
        </div>
    </div>

</section>

JeCenterWeb/Areas/scp/Views/Discuss/NotiEmp.cshtml
@model IEnumerable<JeCenterWeb.Models.CNotifications>
@{
    ViewData["Title"] = "Notifications";
}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <partial name="_NotiMenu" />
            </div>
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title"> الموظفين </h3>
                        <div class="card-tools">
                            <a asp-action="AddNotiEmp" asp-controller="Discuss" asp-area="scp" class="btn btn-primary btn-sm"> <i class="fa fa-plus"></i> أشعار جديد</a>
                        </div>
                    </div>
                    <div class="card-body p-0">

                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th style="width:150px;" class="text-center">

                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.NotiTitel)
                                        </th>
                                        <th style="width:200px;" class="text-center">
                                            التاريخ
                                        </th>
                                        <th style="width:150px;" class="text-center">
                                            الوقت
                                        </th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td class="text-center">
                                                <a asp-area="scp" asp-controller="Discuss" asp-route-id="@item.NotificationId" asp-action="DeleteNotification" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a> |
                                                <a asp-area="scp" asp-controller="Discuss" asp-route-id="@item.NotificationId" asp-action="ReadedNotification" class="btn btn-info btn-sm"><i class="fa fa-eye"></i></a>

                                            </td>
                                            <td class="mailbox-name">
                                                @item.NotiTitel
                                            </td>
                                            <td class="text-center">
                                                @Convert.ToDateTime(item.CreatedDate).ToString("yyyy-MM-dd")
                                            </td>
                                            <td class="text-center">
                                                @Convert.ToDateTime(item.CreatedDate).ToString("t")
                                            </td>

                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

JeCenterWeb/Areas/scp/Views/Discuss/NotiGroup.cshtml
@model IEnumerable<JeCenterWeb.Models.GNotifications>
@{
    ViewData["Title"] = "Notifications";
}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <partial name="_NotiMenu" />
            </div>
            <div class="col-md-9">
                <div class="card card-success card-outline">
                    <div class="card-header">
                        <h3 class="card-title"> الطلبة </h3>
                        <div class="card-tools">
                            <a asp-action="AddNotiGroup" asp-controller="Discuss" asp-area="scp" class="btn btn-success btn-sm"> <i class="fa fa-plus"></i> أشعار جديد</a>
                        </div>
                    </div>
                    <div class="card-body p-0">

                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th style="width:150px;" class="text-center">

                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.NotiTitel)
                                        </th>
                                        <th style="width:200px;" class="text-center">
                                            التاريخ
                                        </th>
                                        <th style="width:150px;" class="text-center">
                                            الوقت
                                        </th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td class="text-center">
                                                <a href="#" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a> |
                                                <a href="#" class="btn btn-info btn-sm"><i class="fa fa-edit"></i></a>

                                            </td>
                                            <td class="mailbox-name">
                                                @item.NotiTitel
                                            </td>
                                            <td class="text-center">
                                                @Convert.ToDateTime(item.CreatedDate).ToString("yyyy-MM-dd")
                                            </td>
                                            <td class="text-center">
                                                @Convert.ToDateTime(item.CreatedDate).ToString("t")
                                            </td>

                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

JeCenterWeb/Areas/scp/Views/Discuss/Notifications.cshtml
@model IEnumerable<JeCenterWeb.Models.UsersNotifications>

@{
    ViewData["Title"] = "Notifications";
}

<style>
    a{
        text-decoration:none;
    }

        a:hover, a:visited, a:link, a:active {
            text-decoration: none;
        }
</style>
<div class="card card-primary card-outline">
    <div class="card-header">
        <h3 class="card-title">Notifications</h3>
    </div>

    <div class="card-body p-0">

        <div class="table-responsive mailbox-messages">
            <table class="table table-hover table-striped">
                <thead>
                    <tr>

                        <th style="width:50px;" class="text-center">

                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CNotifications.NotiTitel)
                        </th>
                        <th style="width:200px;" class="text-center">
                            التاريخ
                        </th>
                        <th style="width:150px;" class="text-center">
                            الوقت
                        </th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        string txtclr = "color: #000 !important;";
                        <tr>
                            <td>
                                 @if (item.Seen == false)
                                {
                                    txtclr = "color: #0072c6 !important;font-weight:bolder;";

                                }
                                else
                                {
                                    <i class="fa fa-eye"></i>
                                }
                            </td>
                            <td class="mailbox-name">
                                <a asp-action="ReadNotification" asp-controller="Discuss" asp-area="scp" asp-route-id="@item.UsersNotificationId" style="@txtclr">  @item.CNotifications.NotiTitel </a>
                            </td>
                            <td class="text-center">
                                @Convert.ToDateTime(item.CNotifications.CreatedDate).ToString("yyyy-MM-dd")
                            </td>
                            <td class="text-center">
                                @Convert.ToDateTime(item.CNotifications.CreatedDate).ToString("t")
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

JeCenterWeb/Areas/scp/Views/Discuss/ReadNotification.cshtml
@model JeCenterWeb.Models.UsersNotifications


@{
    ViewData["Title"] = "Notifications";
}



<div class="card card-primary card-outline">
     <div class="card-body p-0">
        <div class="card-header">
            <h3 class="card-title">Read Mail</h3>

            <div class="card-tools">
               @*  <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a> *@
                <a asp-action="Notifications" asp-controller="Discuss" asp-area="scp" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>
            </div>
        </div>
        <div class="card-body p-0">
            <div class="mailbox-read-info">
                <h5> @Model.CNotifications.NotiTitel</h5>
                <h6>
                    <span class="mailbox-read-time float-right"> @Convert.ToDateTime(Model.CreatedDate).ToString("yyyy-MM-dd") - @Convert.ToDateTime(Model.CreatedDate).ToString("t") </span>  
                </h6>
            </div>
            <div class="mailbox-read-message">
                @Html.Raw(Model.CNotifications.NotificationNote)
            </div>
        </div>
    </div>
</div>

JeCenterWeb/Areas/scp/Views/Discuss/ReadedNotification.cshtml
@model JeCenterWeb.Models.ViewModel.ReadedNotificationViewModel


@{
    ViewData["Title"] = "Notifications";
}


<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <partial name="_NotiMenu" />
            </div>
            <div class="col-md-9">
                <div class="card card-primary card-outline">

                    <div class="card-header">
                        <h3 class="card-title"> الطلبة </h3>
                        <div class="card-tools">
                            <a asp-action="AddNotiEmp" asp-controller="Discuss" asp-area="scp" class="btn btn-primary btn-sm"> <i class="fa fa-plus"></i> أشعار جديد</a>
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <div class="mailbox-read-info">
                            <h5> @Model.cNotifications.NotiTitel</h5>
                            <h6>
                                <span class="mailbox-read-time float-right"> @Model.cNotifications.CreatedDate  </span>
                            </h6>
                        </div>
                        <div class="mailbox-read-message">
                            @Html.Raw(Model.cNotifications.NotificationNote)
                        </div>
                    </div>
                    <hr />
                    <div class="card-body p-0 container ">
                        @foreach (var item in Model.NotificationUserSeen)
                        {
                            <div class="row">
                                <div class="col-md-1"></div>
                                <div class="col-md-1 text-center">
                                    @if (item.Seen == true)
                                    {
                                        <i class="fa fa-eye"></i>
                                    }
                                </div>
                                <div class="col-md-6">
                                    @item.UserName
                                </div>
                                <div class="col-md-4 text-center">
                                    @item.SeenDate  
                                </div>
                               
                             
                            </div>
                            <hr />
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>